db.inventory.insert({_id: 1, "name": "Pizza Dough", "description": "description28", "quantity": 250000});
db.inventory.insert({_id: 2, "name": "Cheese", "description": "description27", "quantity": 250000});
db.inventory.insert({_id: 3, "name": "ham", "description": "description16", "quantity": 250000});
db.inventory.insert({_id: 4, "name": "pepperoni", "description": "description23", "quantity": 250000});
db.inventory.insert({_id: 5, "name": "beef", "description": "description9", "quantity": 250000});
db.inventory.insert({_id: 6, "name": "salami", "description": "description18", "quantity": 250000});
db.inventory.insert({_id: 7, "name": "anchovies", "description": "description12", "quantity": 250000});
db.inventory.insert({_id: 8, "name": "italian sausage", "description": "description7", "quantity": 250000});
db.inventory.insert({_id: 9, "name": "philly steak", "description": "description13", "quantity": 250000});
db.inventory.insert({_id: 10, "name": "bacon", "description": "description22", "quantity": 250000});
db.inventory.insert({_id: 11, "name": "chicken", "description": "description22", "quantity": 250000});
db.inventory.insert({_id: 12, "name": "shredded parmesan asiago", "description": "description18", "quantity": 250000});
db.inventory.insert({_id: 13, "name": "banana peppers", "description": "description7", "quantity": 250000});
db.inventory.insert({_id: 14, "name": "green peppers", "description": "description24", "quantity": 250000});
db.inventory.insert({_id: 15, "name": "mushrooms", "description": "description12", "quantity": 250000});
db.inventory.insert({_id: 16, "name": "onions", "description": "description22", "quantity": 250000});
db.inventory.insert({_id: 17, "name": "spinach", "description": "description9", "quantity": 250000});
db.inventory.insert({_id: 18, "name": "feta cheese", "description": "description21", "quantity": 250000});
db.inventory.insert({_id: 19, "name": "shredded provolone", "description": "description28", "quantity": 250000});
db.inventory.insert({_id: 20, "name": "black olives", "description": "description24", "quantity": 250000});
db.inventory.insert({_id: 21, "name": "jalapeno peppers", "description": "description1", "quantity": 250000});
db.inventory.insert({_id: 22, "name": "pineapple", "description": "description20", "quantity": 250000});
db.inventory.insert({_id: 23, "name": "roasted red peppers", "description": "description8", "quantity": 250000});
db.inventory.insert({_id: 24, "name": "diced tomatoes", "description": "description19", "quantity": 250000});
db.inventory.insert({_id: 25, "name": "Classic Tomato Sauce", "description": "description20", "quantity": 250000});
db.inventory.insert({_id: 26, "name": "Marinara", "description": "description8", "quantity": 250000});
db.inventory.insert({_id: 27, "name": "BBQ Sauce", "description": "description22", "quantity": 250000});
db.inventory.insert({_id: 28, "name": "Alfredo", "description": "description5", "quantity": 250000});
db.inventory.insert({_id: 29, "name": "Garlic Parmesan White Sauce", "description": "description13", "quantity": 250000});
