print("Loading Users...");
load('loadUsers.js');
print("Users Entered.");
print("Loading Inventory...");
load('loadIngredients.js');
print("Inventory Entered.");
print("Loading Recipes...");
load('loadRecipes.js');
print("Recipes Entered.");
print("Loading Orders...");
load('loadOrders.js');
print("Orders Entered.");